<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  * {
  box-sizing: border-box;
}
 

.container {
  position:center;
  max-width: 800px;
  margin: 0 auto;
}

.container img {vertical-align: center;}

.container .content {
  position:absolute;
  bottom: 0;
  background: rgb(0, 0, 0); /* Fallback color */
  background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */
  color: #f1f1f1;
  width: 50%;
  padding: 10px;
}

input[type=text], input[type=password] {
  width: 100%;
  padding: 10px 10px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

button {
  background-color:  DodgerBlue;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

button:hover {
  opacity: 0.8;
}

.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: DodgerBlue;
}

.imgcontainer {
  text-align: center;
  margin: 200px  150px 0;
}

img.avatar {
  width: 30%;
  border-radius: 40%;
}

.container {
  padding: 10px;
}

span.psw {
  float: center;
  padding-top: 10px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: center;
  }
  .cancelbtn {
     width: 100%;
  }
}
.error {color: #FF0000;}
</style>
</head>
<body>
 
  <div class="container">
  <img src="bg.png" height="100%", alt="Notebook" style="width:100%;">
  <div class="content">
 
</head>
  <body>

 
<div class="bg-img">
<body bgcolor="Black">

   
   

<form action="add9.php" method="post">

  <div class="imgcontainer">
    <img src="female.jpg" alt="Abhijeet" class="avatar">
  </div>
<p><CENTER><B><h5>Dr. Ashwini Shinde</h5></td>

<br>MD - Dermatology , Venereology & Leprosy, MBBS
</Br>
<br>Dermatologist, Pediatric Dermatologist, Hair Transplant Surgeon
26 Years Experience Overall  (17 years as specialist)
</Br>



<BR>WORK AT: Dermatologist,Aesthetic Dermatologist and Dermatosurgeon in Hadapsar, Pune  </BR>
<br>EMAIL ID: AshwiniShinde123@gmail.com</Br>
<br>DOCTOR FEES: ₹500 Consultation fee at clinic</BR>
<BR>CONTACT NO: 9065387254</Br>
<BR><B> DOCTOR AVAILABLE ON:MON-SUNDAY 12:00AM-09:00PM</B></Br>




</B></P></CENTER>
  <div class="container">
 

     


    <button type="submit">ADD DOCTOR</button>
    <label>

</form>

</body>
</html>
