<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>

html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

body {font-family: georgia;}
* {box-sizing: border-box;} 

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 40px;
  padding: 0 10px;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0);
}

.container {
  padding: 0 16px;
   color: white;

}


.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
  text-decoration: none;
}
 

.title {
  color: white;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color:  DodgerBlue;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color:  DodgerBlue;
}

  

</style>

<style type='text/css'>
  
  h1 {
    color:pink;
  }

   h2 {
    color:white;
  }
  
   
</style>
</head>
 
   
 
 
 
 
<h1><CENTER>E-HEALTHCARE ONLINE CONSULTATION AND MEDICAL SUBSCRIPTION</CENTER></h1><BR><BR>

<h2><CENTER>BUY MEDICIENES ONLINE</h2></CENTER><BR><BR>

</head>
<body>

   
  
<div class="bg-img"> 
<body bgcolor="BLACK">


  
<div class="row">
  <div class="column">
    <div class="card">


      <img src="m1.jpeg" style="width:100%">
      <div class="container">
         <center>
        <p class="title"><B>MEDLIFE</B></p>
      </center>
        
        
       
           <button class="button" onclick ="document.location='https://www.medlife.com/healthstore2?ef_id=Cj0KCQjwpdqDBhCSARIsAEUJ0hPRRuUDawQViAktXpIzDQnz4rGGljc8Oo_SL7ybBykhWjEGTHjq4NEaAv5qEALw_wcB:G:s&s_kwcid=AL!5681!3!504799208763!e!!g!!online%20medicine&utm_source=google&utm_campaign=sem_Generic_Top_Performing_Keywords_Pan_India&utm_medium=sem&utm_term=9248899435:107181205903:kwd-47242171:504799208763&gclid=Cj0KCQjwpdqDBhCSARIsAEUJ0hPRRuUDawQViAktXpIzDQnz4rGGljc8Oo_SL7ybBykhWjEGTHjq4NEaAv5qEALw_wcB'"> VISIT WEBSITE </a></button>

          
      </div>
    </div>
  </div>

  <div class="row">
  <div class="column">
    <div class="card">


      <img src="m5.jpeg"  style="width:100%">
      <div class="container">
         <center>
        <p class="title"><B>1MG</B></p>
      </center>
        

 <button class="button" onclick ="document.location='https://www.1mg.com/myoffers?utm_source=google&utm_medium=cpc&utm_campaign=Search-Generic-Med-Rest-Exact&utm_keyword=online%20medical&utm_adgroup={adgroup}&gclid=Cj0KCQjwpdqDBhCSARIsAEUJ0hPhNSi31djfKmmAQWhOYICd0jPCZlgg29CM78lhXOFgu-n61yDcg84aAseKEALw_wcB'"> VISIT WEBSITE  </a></button>
       
      
      </div>
    </div>
  </div>


  <div class="column">
    <div class="card">
      <img src="m4.jpeg"  style="width:100%">
      <div class="container">
         <center>
        <b><p class="title">NETMEDS</p></b>
      </center>

        
       
        </center>

      <button class="button" onclick ="document.location='https://www.netmeds.com/healthstore?gclid=Cj0KCQjwpdqDBhCSARIsAEUJ0hN1zDNsEYsiszDC1-BQT0yoX_LtjcYE05MJHn_U3R4f3Frp9sJHTQYaAudjEALw_wcB'">VISIT WEBSITE </a></button> 
          
          
      </div>
    </div>
  </div>


  <div class="row">
  <div class="column">
    <div class="card">
      <img src="m3.jpeg" style="width:100%">
      <div class="container">
        <center>
        
        <p class="title">PHARMEASY</p>
      </center>
         <button class="button" onclick ="document.location='https://pharmeasy.in/'">VISIT WEBSITE </a></button> 
          
       
          
          
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="m6.jpeg" alt="Neelam" style="width:100%">
      <div class="container">
        <center>
        
        <p class="title">AMAZON</p>
      </center>
       
       <button class="button" onclick ="document.location='https://www.amazon.in/b?ie=UTF8&node=16068806031'"> VISIT WEBSITE </a></button> 
          
       
      </div>
    </div>
  </div>
 
  <div class="column">
    <div class="card">
      <img src="m2.jpeg" alt="Swapnil" style="width:100%">
      <div class="container">
        <center>
      
        <p class="title">MEDPLUS SMART</p>
      </center>
       
         <button class="button" onclick ="document.location='https://www.medplusmart.com/'">VISITE WEBSITE </a></button> 
            
          
      </div>
    </div>
  </div>
 
    </div>
  </div>

 
          
          
      </div>
    </div>
  </div>
 
    </div>
  </div>
 
    </div>
  </div>
 
      </div>
    </div>
  </div>
 
</div>

</body>
</html>