   
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  * {
  box-sizing: border-box;
}
  

.container {
  position:center;
  max-width: 1800px;
  margin: 0 auto;
}

.container img {vertical-align: center;}

.container .content {
  position:absolute;
  bottom: 0;
  background: rgb(0, 0, 0); /* Fallback color */
  background: rgba(0, 0, 0, 0.3); /* Black background with 0.5 opacity */
  color: black;
  width: 100%;
  padding: 150px;
  font-size: 20px;
}

body {
  font-family: 'georgia';
}

.button {
  background-color:grey; /* Green */
  border: none;
  color: white;
  padding: 70px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 25px;
  margin: 15px 15px;
  cursor: pointer;
  box-shadow: 0 9px #999;
}
.button:hover {background-color:lightgrey}

.button:active {
  background-color: lightgrey;
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}


.button1 {border-radius:500%;}

.button2 {border-radius:500%;}

.button3 {border-radius:500%;}
 
body {
  overflow-y: hidden; /* Hide vertical scrollbar */
  overflow-x: hidden; /* Hide horizontal scrollbar */
}

<style type='text/css'>
  body {
    background-color: black;
  }
  
  p {
    color:lightgreen;
  }
 h1
 {
  color:pink;
 }
   
 .btn {
  background-color: dodgerblue;
  color: white;
  padding: 12px;
  margin: 10px 0;
  border: none;
  width: 100%;
  border-radius: 3px;
  cursor: pointer;
  font-size: 17px;
}

.btn:hover {
  background-color: dodgerblue;
} 
</style>
</head>
</style>
</head>
<body>
 
 <form action="check2.php">
  <div class="container">
  <img src="pa.webp " height="150%", alt="Notebook" style="width:100%;">
  <div class="content">
 

  
<div class="bg-img"> 
<body bgcolor="black">



<center><b><h1>E-HEALTHCARE ONLINE CONSULTATION AND MEDICAL SUBSCRIPTION</h1></center></b><br><br>

 
 
<center><b><p>PAY DOCTORS FEES HERE....</p></b> </center>
 <center><b><p>AND BUY MEDICIENES AND GET SOME DISCOUNTS ON IT.....</p></b> </center>
  
    
 <center> <a href="https://pay.google.com/gp/w/u/0/home/signup" style="text-decoration: none;" target="_blank">
   <img src="https://seeklogo.com/images/G/google-pay-tez-logo-CFC8957086-seeklogo.com.png" width="200" height="200"/>_____</a>
 
  <a href=" https://www.amazon.in/amazonpay/home?ref_=apay_logo_APayDashboard" style="text-decoration: none;" target="_blank">
   <img src="https://cdn4.iconfinder.com/data/icons/circle-payment/32/payment_006-amazon-512.png" width="200" height="200"/>_____</a>

       
   <a href="https://paytm.com/" style="text-decoration: none;" target="_blank">
   <img src="https://image.flaticon.com/icons/png/512/825/825454.png" width="200" height="200"/>____
</a>
<a href="med.php" style="text-decoration: none;" target="_blank">
   <img src="https://cdn4.iconfinder.com/data/icons/eldorado-medicine/40/pill_drugs-512.png" width="200" height="200"/>
</a>

 </center>
 
  
<input type="submit" value="Make Payment Using Cards" class="btn">
          
 

 </head>
 </body> 
</html>